name: Build and deploy to VPS via SSH-SCP

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm install

      - name: Create .env.production file
        run: echo '${{ vars.ENV_PRODUCTION }}' > .env.production

      - name: Build assets
        run: npm run build

      - name: Display built files
        run: ls -R dist/

      - name: Upload built content
        uses: actions/upload-artifact@v4
        with:
          name: built-files
          path: dist/
          retention-days: 14

  deploy:
    name: Deploy via SCP
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: production
    steps:
      - name: Download built content
        uses: actions/download-artifact@v4
        with:
          name: built-files
          path: dist

      - name: Display downloaded content
        run: ls -R dist/

      - name: Copy artifact to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          target: ${{ secrets.FILES_PATH }}
          source: dist/*
          strip_components: 1
          rm: true
